services:
  db:
    image: postgres:16-bullseye
    container_name: db
    restart: unless-stopped
    ports:
      - "54321:${DB_PORT:-5432}"
    environment:
      - POSTGRES_DB=${DB_NAME:-api}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-api}']
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - task

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api
    hostname: api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    entrypoint: > 
      bash -c "
        python3 manage.py collectstatic --noinput
        python3 manage.py migrate
        gunicorn settings.wsgi:application --bind 0.0.0.0:8000 --reload --workers 1
      "
    volumes:
      - ./api/:/opt/app
    networks:
      - task

networks:
  task:
    driver: bridge

volumes:
  postgres_data: